Add first page
OlgaVasilevskaya/MovieApp pull request #1
Opened 2022-07-02 15:53 UTC by OlgaVasilevskaya

Add first page

2022-07-03 17:24 UTC, kathrynowy requested changes

2022-07-03 17:24 UTC, kathrynowy commented on src/App.js
> +    <div className='app'>
обычно мы эту обертку выносим в кажду страницу отдельно, тк они могут отличаться по стилям
а на самом верху мы уже оставляем только роуты

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Button/Button.jsx
> +      <button>Buy ticket</button>
do you need div here?

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Button/Button.jsx
> +      <button>Buy ticket</button>
rename file to index.jsx

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +import Spinner from '../Spinner/Spinner';
style import at the end

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +import Spinner from '../Spinner/Spinner';
to remove this Spinner/Spinner dublicate - rename file to index.jsx

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +  const {eventId} = useParams();
```suggestion
  const [movie, setMovie] = useState([]);
  
  const [isLoading, setIsLoading] = useState(false);
  
  const [isError, setIsError] = useState(true);
  
  const {eventId} = useParams();
```

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +      setIsError(false);
do you need this? i suppose isError variable is false even if you don't write setIsError(false);

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +      }
? if you have no errors you throw an error..

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +        alert(e.message);
you should write setIsError here ( true)

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +                </div>
move to a separate component "Movie"

2022-07-03 17:24 UTC, kathrynowy commented on src/components/ErrorMessage/ErrorMessage.jsx
> +  return (
explicit return please

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +import SearchInput from '../../components/SearchInput/SearchInput';
separate imports for components and assets

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +import SearchInput from '../../components/SearchInput/SearchInput';
and styles at the end

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +  return (
explicit return

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +import Movie from '../Movie/Movie';
same

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +  const [isError, setIsError] = useState(true);
same

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +    fetchItems([]);
why do you need [] here?

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +  const fetchItems = useCallback( async () => {
```suggestion
  const fetchItems = useCallback(async () => {
```

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +      }
same

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +      setIsError(false);
same

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +                </div>
why do you need map here?

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Page404/Page404.js
> +  return (
same

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Page404/Page404.js
> +const Page404 = () => {
NotFoundPage

2022-07-03 17:24 UTC, kathrynowy commented on src/components/Page404/Page404.js
> +const Page404 = () => {
import React

2022-07-03 17:24 UTC, kathrynowy commented on src/components/SearchInput/SearchInput.jsx
> +}
```suggestion
const SearchInput = () => (
    <div className='search'>
      <input type="text" placeholder='Search movie'/>
    </div>
  );
```

2022-07-04 21:33 UTC, kathrynowy requested changes

2022-07-04 21:33 UTC, kathrynowy commented on src/App.js
> +}
use const and explicit return

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Button/index.jsx
> +    <button className='button-buy'>Buy ticket</button>
```suggestion
    <button className='buy-button'>Buy ticket</button>
```

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Button/index.jsx
> +    <button className='button-buy'>Buy ticket</button>
adj and then noun

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Detail/detail.scss
> +}
eof

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Detail/index.jsx
> +  const {detail} = props;
details

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Detail/index.jsx
> +  const {detail} = props;
use word details
you don't have one detail)))

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +import React, {useState, useEffect} from 'react';
```suggestion
import React, { useState, useEffect } from 'react';
```
try to paste space after you open { and before closing }

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +function Details({ match }) {
const

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +  const {eventId} = useParams();
```suggestion
  const { eventId } = useParams();
```

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +  const fetchItem = async () => {
fetchMovieDetails

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +      }
вызовется ли это когда-нибудь? 
(нет)

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +    }
remove logs
before every PR we should remove logs
other developers don't need our logs)

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +              {details.map((d) => <Detail key={d.eventId} detail={d} />)}
такс, шо за detail?

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +      setDetails(resultList);
здесь не массив, а обьект, начальное значение тоже {}
```suggestion
      setDetails(movieDetails[0]);
```

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +      const resultList = await data.json();
```suggestion
      const movieDetails = await data.json();
```

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +            // не получается без map вывести values. Наведи на мысль, пжл
написала выше и в лс

2022-07-04 21:33 UTC, kathrynowy commented on src/components/ErrorMessage/index.jsx
> +    <div className='error-message'>404 not found, we have no such page</div>
```suggestion
    <div className='error-message'>
       404 not found, we have no such page
     </div>
```

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +import SearchInput from '../SearchInput';
fitsly components and then assets

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Movie/index.jsx
> +
const { bannerLink, name, ageLimit } = movie;

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +  const fetchItems = useCallback(async () => {
fetchMovies

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Details/Details.jsx
> +  const fetchItem = async () => {
useCallback

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +      }
same

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +        console.log(setIsError, 'setIsError');
same

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +import React, {useState, useEffect, useCallback} from 'react';
rename file to index.jsx

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +  const [isError, setIsError] = useState(true);
isError should be false as default
do you have error when you component is rendered the first time? no

2022-07-04 21:33 UTC, kathrynowy commented on src/components/NotFoundPage/NotFoundPage.jsx
> +    </div>
have you forgotten about separating html?)

2022-07-04 21:33 UTC, kathrynowy commented on src/components/NotFoundPage/NotFoundPage.jsx
> +    </div>
```suggestion
    <div className='page-404'>
      <ErrorMessage />
      
      <Link to='/'>
        <button>Go to home page</button>
      </Link>
    </div>
```

2022-07-04 21:33 UTC, kathrynowy commented on src/components/NotFoundPage/NotFoundPage.jsx
> +const Page404 = () => {
NotFoundPage

2022-07-04 21:33 UTC, kathrynowy commented on src/components/SearchInput/index.jsx
> +  </div>
why do you need div?

2022-07-04 21:33 UTC, kathrynowy commented on src/components/Spinner/index.jsx
> +  return (
explicit

2022-07-10 19:14 UTC, kathrynowy requested changes

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Button/index.jsx
> +      <button className='buy-button'>Buy ticket</button>
```suggestion
      <button className="buy-button">Buy ticket</button>
```

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Button/index.jsx
> +    <div>
why do you need a div here?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Button/index.jsx
> +  return (
remove return

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Details/index.jsx
> +        `https://soft.silverscreen.by:8443/wssite/webapi/event/data?filter=%7B%22event%22:%22${eventId}%22,%22city%22:%221%22%7D&extended=true`
why do you need an empty line?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Details/index.jsx
> +      if(!isError) {
?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Details/index.jsx
> +      if(!isError) {
try to think what is it?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Details/index.jsx
> +            </>
why do you need a fragment here?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/ErrorMessage/index.jsx
> +    <div className='error-message'>
same

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Modal/Modal.jsx
> +
?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Movie/index.jsx
> +      <div className='movie-img-wrapper'>
why do you need a div?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +        : setCity(5)
1 line

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +  const handleChange = (e) => {
useCallback

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +                {console.log(city)}
remove

2022-07-10 19:14 UTC, kathrynowy commented on src/components/Movies/movies.scss
> +}
eof

2022-07-10 19:14 UTC, kathrynowy commented on src/components/ScrollUp/ScrollUp.jsx
> +        }
1 line

2022-07-10 19:14 UTC, kathrynowy commented on src/components/ScrollUp/ScrollUp.jsx
> +            {showBtn && (
isBtnShown

2022-07-10 19:14 UTC, kathrynowy commented on src/components/ScrollUp/ScrollUp.jsx
> +                <FaAngleUp className="icon" onClick={handleScrollUp}
fa angle?

2022-07-10 19:14 UTC, kathrynowy commented on src/components/SearchInput/index.jsx
> +
why do u need an empty line?

2022-07-22 05:29 UTC, OlgaVasilevskaya commented on src/App.js
> +    <div className='app'>
fixed

2022-07-22 05:29 UTC, OlgaVasilevskaya commented on src/components/Button/Button.jsx
> +      <button>Buy ticket</button>
fixed

2022-07-22 05:29 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +import Spinner from '../Spinner/Spinner';
fixed

2022-07-22 05:29 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +import Spinner from '../Spinner/Spinner';
fixed

2022-07-22 05:29 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +  const {eventId} = useParams();
fixed

2022-07-22 05:30 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +      setIsError(false);
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +        alert(e.message);
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +                </div>
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/ErrorMessage/ErrorMessage.jsx
> +  return (
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/Header/Header.jsx
> +import SearchInput from '../../components/SearchInput/SearchInput';
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/Header/Header.jsx
> +  return (
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +import Movie from '../Movie/Movie';
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +  const [isError, setIsError] = useState(true);
fixed

2022-07-22 05:31 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +    fetchItems([]);
fixed

2022-07-22 05:32 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +  const fetchItems = useCallback( async () => {
fixed

2022-07-22 05:32 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +      }
fixed

2022-07-22 05:32 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +      setIsError(false);
fixed

2022-07-22 05:32 UTC, OlgaVasilevskaya commented on src/components/Page404/Page404.js
> +  return (
fixed

2022-07-22 05:32 UTC, OlgaVasilevskaya commented on src/components/Page404/Page404.js
> +const Page404 = () => {
fixed

2022-07-22 05:32 UTC, OlgaVasilevskaya commented on src/components/SearchInput/SearchInput.jsx
> +}
fixed

2022-07-22 05:32 UTC, OlgaVasilevskaya commented on src/App.js
> +}
fixed

2022-07-22 05:33 UTC, OlgaVasilevskaya commented on src/components/Button/index.jsx
> +    <button className='button-buy'>Buy ticket</button>
fixed

2022-07-22 05:33 UTC, OlgaVasilevskaya commented on src/components/Detail/detail.scss
> +}
fixed

2022-07-22 05:33 UTC, OlgaVasilevskaya commented on src/components/Detail/index.jsx
> +  const {detail} = props;
fixed

2022-07-22 05:33 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +import React, {useState, useEffect} from 'react';
fixed

2022-07-22 05:34 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +function Details({ match }) {
fixed

2022-07-22 05:34 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +  const {eventId} = useParams();
fixed

2022-07-22 05:35 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +  const fetchItem = async () => {
fixed

2022-07-22 05:36 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +    }
fixed

2022-07-22 05:36 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +              {details.map((d) => <Detail key={d.eventId} detail={d} />)}
fixed

2022-07-22 05:36 UTC, kathrynowy requested changes

2022-07-22 05:36 UTC, kathrynowy commented on src/components/Details/index.jsx
> +        setIsError(true);
if there is an error, you set state and do what?

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +    setFormType(true);
why is this above the state declarations?

form type true? what does it mean

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +  const handleOpen = () => setIsActive(true);
same

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +    if((password === repeatPassword) && (password ?? repeatPassword)) {
```suggestion
    if((password === repeatPassword) && (password ?? repeatPassword)) {
```

i don't really get why do you use ?? here?

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +    }
?

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +    localStorage.setItem('users', JSON.stringify([...users, newUser]));
where is the check for an existing user?

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +    console.log(userEmail2, 'userEmail2')
?

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +    setFormType(true);
?

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +            (<Box sx={style}>
move these boxes to components

SignIn
SignUp

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +                <button onClick={handleSubmit} className="submit" disabled={(!email, !password)}>
disabled value calculate in use memo

2022-07-22 05:36 UTC, kathrynowy commented on src/components/GeneralModal/index.jsx
> +                <button onClick={handleSubmit} className="submit" disabled={(!email, !firstName, !lastName, !phone, !password, !repeatPassword)}>
same

2022-07-22 05:36 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +    e.target.value === 'minsk' ? setCity(1) : setCity(5)
write setCity only 1 time please
and move condition inside invoking

2022-07-22 05:36 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +                <select className='movies-city' onChange={handleChange}>
create controlled select pls

2022-07-22 05:36 UTC, kathrynowy commented on src/components/ScrollUp/index.jsx
> +      (window.scrollY > 200) ?  setIsBtnShown(true) : setIsBtnShown(false);
```suggestion
   setIsBtnShown(window.scrollY > 200);
```

2022-07-22 05:36 UTC, kathrynowy commented on src/components/ScrollUp/scrollUp.scss
> +  border: 2px solid #fff;
all colors to scss colors file

2022-07-22 05:36 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +      setDetails(resultList);
fixed

2022-07-22 05:36 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +      const resultList = await data.json();
fixed

2022-07-22 05:39 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +            // не получается без map вывести values. Наведи на мысль, пжл
fixed

2022-07-22 05:45 UTC, OlgaVasilevskaya commented on src/components/ErrorMessage/index.jsx
> +    <div className='error-message'>404 not found, we have no such page</div>
fixed

2022-07-22 05:46 UTC, OlgaVasilevskaya commented on src/components/Header/Header.jsx
> +import SearchInput from '../SearchInput';
fixed

2022-07-22 05:46 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +  const fetchItems = useCallback(async () => {
fixed

2022-07-22 05:46 UTC, OlgaVasilevskaya commented on src/components/Details/Details.jsx
> +  const fetchItem = async () => {
fixed

2022-07-22 05:46 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +      }
fixed

2022-07-22 05:47 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +        console.log(setIsError, 'setIsError');
fixed

2022-07-22 05:47 UTC, OlgaVasilevskaya commented on src/components/Movies/Movies.jsx
> +  const [isError, setIsError] = useState(true);
fixed

2022-07-22 05:47 UTC, OlgaVasilevskaya commented on src/components/NotFoundPage/NotFoundPage.jsx
> +    </div>
fixed

2022-07-22 05:51 UTC, OlgaVasilevskaya commented on src/components/NotFoundPage/NotFoundPage.jsx
> +const Page404 = () => {
fixed

2022-07-22 05:52 UTC, OlgaVasilevskaya commented on src/components/Spinner/index.jsx
> +  return (
fixed

2022-07-22 05:52 UTC, OlgaVasilevskaya commented on src/App.js
> +  return (
fixed

2022-07-22 05:52 UTC, OlgaVasilevskaya commented on src/components/Button/index.jsx
> +}
fixed

2022-07-22 05:53 UTC, OlgaVasilevskaya commented on src/components/Button/index.jsx
> +    <div>
fixed

2022-07-22 05:53 UTC, OlgaVasilevskaya commented on src/components/Button/index.jsx
> +  return (
fixed

2022-07-22 05:53 UTC, OlgaVasilevskaya commented on src/components/Details/index.jsx
> +      if(!isError) {
fixed

2022-07-22 05:54 UTC, OlgaVasilevskaya commented on src/components/ErrorMessage/index.jsx
> +    <div className='error-message'>
fixed

2022-07-22 05:54 UTC, OlgaVasilevskaya commented on src/components/Modal/Modal.jsx
> +
fixed

2022-07-22 05:54 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
> +        : setCity(5)
fixed

2022-07-22 05:54 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
> +  const handleChange = (e) => {
fixed

2022-07-22 05:54 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
> +                {console.log(city)}
fixed

2022-07-22 05:55 UTC, OlgaVasilevskaya commented on src/components/Movies/movies.scss
> +}
fixed

2022-07-22 05:55 UTC, OlgaVasilevskaya commented on src/components/ScrollUp/ScrollUp.jsx
> +        }
fixed

2022-07-22 05:55 UTC, OlgaVasilevskaya commented on src/components/ScrollUp/ScrollUp.jsx
> +            {showBtn && (
fixed

2022-07-22 05:55 UTC, OlgaVasilevskaya commented on src/components/ScrollUp/ScrollUp.jsx
> +                <FaAngleUp className="icon" onClick={handleScrollUp}
fixed

2022-07-29 06:25 UTC, OlgaVasilevskaya commented on src/components/Details/index.jsx
> +        setIsError(true);
fixed

2022-07-29 06:25 UTC, OlgaVasilevskaya commented on src/components/GeneralModal/index.jsx
> +    setFormType(true);
fixed

2022-07-29 06:25 UTC, OlgaVasilevskaya commented on src/components/GeneralModal/index.jsx
> +  const handleOpen = () => setIsActive(true);
fixed

2022-07-29 06:25 UTC, OlgaVasilevskaya commented on src/components/GeneralModal/index.jsx
> +    if((password === repeatPassword) && (password ?? repeatPassword)) {
fixed

2022-07-29 06:26 UTC, OlgaVasilevskaya commented on src/components/GeneralModal/index.jsx
> +    }
fixed

2022-07-29 06:26 UTC, OlgaVasilevskaya commented on src/components/GeneralModal/index.jsx
> +    localStorage.setItem('users', JSON.stringify([...users, newUser]));
fixed

2022-07-29 06:26 UTC, OlgaVasilevskaya commented on src/components/GeneralModal/index.jsx
> +    console.log(userEmail2, 'userEmail2')
fixed

2022-07-29 06:27 UTC, OlgaVasilevskaya commented on src/components/GeneralModal/index.jsx
> +    setFormType(true);
fixed

2022-07-29 06:35 UTC, OlgaVasilevskaya commented on src/components/ScrollUp/index.jsx
> +      (window.scrollY > 200) ?  setIsBtnShown(true) : setIsBtnShown(false);
fixed

2022-07-29 06:44 UTC, OlgaVasilevskaya commented on src/components/ScrollUp/scrollUp.scss
> +  border: 2px solid #fff;
fixed

2022-07-29 06:51 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
> +                <select className='movies-city' onChange={handleChange}>
fixed

2022-07-29 06:51 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
> +    e.target.value === 'minsk' ? setCity(1) : setCity(5)
fixed

2022-09-03 06:38 UTC, kathrynowy requested changes

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Button/index.jsx
> +  return (
do you need an explicit return?

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Button/withButton.js
> +export default withButton;
eof

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Details/index.jsx
> +          </>
move this checks above

if (isError) {
return <div>dffddfdf</div>
}

and you can leave here only isLoading , or even move isLoading above as well

2022-09-03 06:38 UTC, kathrynowy commented on src/components/DetailsElements/index.jsx
> +import cls from 'classnames';
move t react import it's also library

2022-09-03 06:38 UTC, kathrynowy commented on src/components/DetailsElements/index.jsx
> +  const isUserPayable = true;
what is this?

2022-09-03 06:38 UTC, kathrynowy commented on src/components/DetailsElements/index.jsx
> +        <Button name={"Click button"} />
you don't need {}. here

2022-09-03 06:38 UTC, kathrynowy commented on src/components/ErrorBoundary/index.jsx
> +    console.log(error, errorInfo, 'error, errorInfo');
we remove logs

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Header/header.scss
> +$primary-color: #9e8888;
move to variables file 

src/styles/variables.css

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Header/header.scss
> +  height: 50px;
use Sass nesting here

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Header/index.jsx
> +    navigate('../users-profile');
move routes to a constant object
and use only obj everywhere

and we don't navigate like this ../

you write only route name

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Header/index.jsx
> +      </div>
you don't need an empty div here)

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Header/index.jsx
> +          <button onClick={handleLogout()}>
why do you need () here?

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +  const [isSignUp, setIsSignUp] = useState('');
make this as 1 object

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +    await sleep(300)
why do you need this?

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +            (<Box sx={style}>
move this to a separate components (signUp/sign in)

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +                    }}
move this to a function

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +                onChange={handleChangeInput('phone')}
create an array of objects

signInInputs

and save there
name, function and value


and paste here a map of this array, inserting only 1 field)

2022-09-03 06:38 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +        isError
same here

2022-09-03 06:38 UTC, kathrynowy commented on src/components/UsersProfile/index.jsx
> +
?

2022-09-03 06:38 UTC, kathrynowy commented on src/components/UsersProfile/index.jsx
> +  const [formError, setFormError] = useState('');
same

2022-09-03 06:38 UTC, kathrynowy commented on src/components/UsersProfile/index.jsx
> +
remove all this

2022-09-03 06:38 UTC, kathrynowy commented on src/routes/index.jsx
> +      <Route path='*' element={<NotFoundPage />}></Route>
create an array of objects and use it as well

2022-09-03 06:38 UTC, kathrynowy commented on src/store/moviesSlice.js
> +      state.entities = payload;
why entities/ name it movies))

2022-09-03 06:38 UTC, kathrynowy commented on src/store/userSlice.js
> +export const selectUsers = (state) => state.user.users;
move this to a selectors file
and use reselect to createSelector

2022-09-03 08:05 UTC, OlgaVasilevskaya commented on src/components/Button/index.jsx
> +  return (
fixed

2022-09-03 08:06 UTC, OlgaVasilevskaya commented on src/components/Button/withButton.js
> +export default withButton;
fixed

2022-09-03 09:05 UTC, OlgaVasilevskaya commented on src/components/Details/index.jsx
> +          </>
fixed

2022-09-03 09:08 UTC, OlgaVasilevskaya commented on src/components/DetailsElements/index.jsx
> +import cls from 'classnames';
fixed

2022-09-03 09:26 UTC, OlgaVasilevskaya commented on src/components/DetailsElements/index.jsx
> +  const isUserPayable = true;
fixed

2022-09-03 09:28 UTC, OlgaVasilevskaya commented on src/components/DetailsElements/index.jsx
> +        <Button name={"Click button"} />
fixed

2022-09-03 09:28 UTC, OlgaVasilevskaya commented on src/components/ErrorBoundary/index.jsx
> +    console.log(error, errorInfo, 'error, errorInfo');
fixed

2022-09-03 09:37 UTC, OlgaVasilevskaya commented on src/components/Header/header.scss
> +$primary-color: #9e8888;
fixed

2022-09-03 09:42 UTC, OlgaVasilevskaya commented on src/components/Header/header.scss
> +  height: 50px;
fixed

2022-09-03 10:05 UTC, OlgaVasilevskaya commented on src/components/Header/index.jsx
> +      </div>
fixed

2022-09-03 10:06 UTC, OlgaVasilevskaya commented on src/components/Header/index.jsx
> +          <button onClick={handleLogout()}>
fixed

2022-09-03 15:41 UTC, OlgaVasilevskaya commented on src/store/moviesSlice.js
> +      state.entities = payload;
fixed

2022-09-04 16:21 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +            (<Box sx={style}>
fixed

2022-09-04 16:59 UTC, OlgaVasilevskaya commented on src/components/Header/index.jsx
> +    navigate('../users-profile');
fixed

2022-09-04 17:04 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +    await sleep(300)
fixed

2022-09-04 17:20 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
> +        isError
fixed

2022-09-04 17:21 UTC, OlgaVasilevskaya commented on src/components/UsersProfile/index.jsx
> +
fixed

2022-09-04 17:37 UTC, OlgaVasilevskaya commented on src/routes/index.jsx
> +      <Route path='*' element={<NotFoundPage />}></Route>
fixed

2022-09-05 09:14 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +  const [isSignUp, setIsSignUp] = useState('');
fixed

2022-09-05 09:15 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +                onChange={handleChangeInput('phone')}
fixed

2022-09-05 09:15 UTC, OlgaVasilevskaya commented on src/components/UsersProfile/index.jsx
> +  const [formError, setFormError] = useState('');
fixed

2022-09-05 09:19 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +                    }}
fixed

2022-09-05 09:21 UTC, OlgaVasilevskaya commented on src/components/UsersProfile/index.jsx
> +
fixed

2022-09-05 17:53 UTC, OlgaVasilevskaya commented on src/store/userSlice.js
> +export const selectUsers = (state) => state.user.users;
fixed

2022-09-05 19:49 UTC, kathrynowy requested changes

2022-09-05 19:49 UTC, kathrynowy commented on src/components/DetailsElements/index.jsx
> +  const currentDay = getWeekDay(date);
move getting the day inside the function))

2022-09-05 19:49 UTC, kathrynowy commented on src/components/DetailsElements/index.jsx
> +  const currentDay = getWeekDay(date);
const date = new Date();

2022-09-05 19:49 UTC, kathrynowy commented on src/components/DetailsElements/index.jsx
> +          'show-offer': currentDay === 'Sat',
move this check to useMemo so it's not recalculated every rerender

2022-09-05 19:49 UTC, kathrynowy commented on src/components/Modal/index.jsx
>      setIsEmailExist('');
if you use naming 'isBlaBlaBla' it should be boolean

2022-09-05 19:49 UTC, kathrynowy commented on src/components/Modal/index.jsx
>      window.alert('LOGIN SUCCESS!')
i would rather add snackbar from material

2022-09-05 19:49 UTC, kathrynowy commented on src/components/Movies/index.jsx
>      return movie.name.toLowerCase().includes(isSearch.toLowerCase());
why return here?

2022-09-05 19:49 UTC, kathrynowy commented on src/components/Movies/index.jsx
>      return movie.name.toLowerCase().includes(isSearch.toLowerCase());
move filtering to useSelector

2022-09-05 19:49 UTC, kathrynowy commented on src/components/Movies/index.jsx
>      return movie.name.toLowerCase().includes(isSearch.toLowerCase());
isSearch is boolean? i suppose no

name it searchQuery for example

2022-09-05 19:49 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +            onChange={debouncedResults}
you forget about indentation

<input 
   type="text" 
   placeholder='Search' 
   onChange={debouncedResults} 
 />
 
 
 as we did in html

2022-09-05 19:49 UTC, kathrynowy commented on src/components/Movies/index.jsx
> +            onChange={debouncedResults}
use input from material

2022-09-05 19:49 UTC, kathrynowy commented on src/routes/index.jsx
> +      <Route path={ROUTES.homePage} element={<Movies />} />
use map here

2022-09-05 19:49 UTC, kathrynowy commented on src/styles/_mixins.scss
> +  color: #1e2222;
? variables

2022-09-05 19:54 UTC, kathrynowy requested changes

2022-09-05 19:54 UTC, kathrynowy commented on src/store/userSlice.js
> +export const selectUsers = (state) => getUsersSelector(state);
you should move this to selectors file

all selectors should be there

2022-09-05 19:54 UTC, kathrynowy commented on src/store/usersSelectors.js
> +export const getUsersSelector = createSelector(getUsers, users => users);
you do it in a wrong way))

2022-09-05 19:54 UTC, kathrynowy commented on src/store/usersSelectors.js
> +export const getUsersSelector = createSelector(getUsers, users => users);
added example in TG

2022-09-05 19:57 UTC, kathrynowy requested changes

2022-09-05 19:57 UTC, kathrynowy commented on src/store/selectors.js
> +export const selectUser = (state) => getUserSelector(state);
same

2022-09-05 20:07 UTC, kathrynowy requested changes

2022-09-05 20:07 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +  const { isOpen } = useSelector(state => state.modal);
movr to selectors

2022-09-05 20:07 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +    setFormType(false);
it's not ok
what does it mean form type true?

2022-09-05 20:07 UTC, kathrynowy commented on src/components/Modal/index.jsx
> +    setFormType(true);
same

rewrite it to one function with type (like we did with select)

2022-09-05 20:07 UTC, kathrynowy commented on src/components/Modal/modal.scss
> +}
eof

2022-09-05 20:07 UTC, kathrynowy commented on src/components/ScrollUp/index.jsx
> +import './scrollUp.scss';
scroll-up

2022-09-06 11:12 UTC, OlgaVasilevskaya commented on src/components/DetailsElements/index.jsx
> +  const currentDay = getWeekDay(date);
fixed

2022-09-06 11:16 UTC, OlgaVasilevskaya commented on src/components/Modal/modal.scss
> +}
fixed

2022-09-06 11:17 UTC, OlgaVasilevskaya commented on src/components/ScrollUp/index.jsx
> +import './scrollUp.scss';
fixed

2022-09-06 18:21 UTC, OlgaVasilevskaya commented on src/components/DetailsElements/index.jsx
> +          'show-offer': currentDay === 'Sat',
fixed

2022-09-06 18:27 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
>      setIsEmailExist('');
fixed

2022-09-09 18:33 UTC, OlgaVasilevskaya commented on src/routes/index.jsx
> +      <Route path={ROUTES.homePage} element={<Movies />} />
fixed

2022-09-09 18:56 UTC, OlgaVasilevskaya commented on src/store/userSlice.js
> +export const selectUsers = (state) => getUsersSelector(state);
fixed

2022-09-09 19:01 UTC, OlgaVasilevskaya commented on src/store/selectors.js
> +export const selectUser = (state) => getUserSelector(state);
fixed

2022-09-09 19:09 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +  const { isOpen } = useSelector(state => state.modal);
fixed

2022-09-10 06:09 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
> +            onChange={debouncedResults}
fixed

2022-09-10 06:09 UTC, OlgaVasilevskaya commented on src/routes/index.jsx
> +      <Route path={ROUTES.homePage} element={<Movies />} />
fixed

2022-09-10 06:09 UTC, OlgaVasilevskaya commented on src/store/userSlice.js
> +export const selectUsers = (state) => getUsersSelector(state);
fixed

2022-09-10 06:32 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
>      window.alert('LOGIN SUCCESS!')
fixed

2022-09-10 10:40 UTC, OlgaVasilevskaya commented on src/components/Movies/index.jsx
>      return movie.name.toLowerCase().includes(isSearch.toLowerCase());
fixed

2022-09-10 10:58 UTC, OlgaVasilevskaya commented on src/styles/_mixins.scss
> +  color: #1e2222;
fixed

2022-09-10 11:12 UTC, OlgaVasilevskaya commented on src/store/usersSelectors.js
> +export const getUsersSelector = createSelector(getUsers, users => users);
fixed

2022-09-10 17:01 UTC, OlgaVasilevskaya commented on src/components/Details/index.jsx
> +      const data = await fetch(
fixed

2022-09-10 20:14 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +    setFormType(true);
fixed

2022-09-10 20:14 UTC, OlgaVasilevskaya commented on src/components/Modal/index.jsx
> +    setFormType(false);
fixed

2022-09-13 10:53 UTC, merged